@drones_HostAddress = http://localhost:3000

GET {{drones_HostAddress}}/api/Drone
Accept: application/json
###
GET {{drones_HostAddress}}/api/Home/FindOrder/{PackageId}
Content-Type: application/json
###
POST {{drones_HostAddress}}/api/Home/GetUserOrders
Content-Type: application/json
###
POST {{drones_HostAddress}}/api/Home/NewOrder
Content-Type: application/json
###
POST {{drones_HostAddress}}/api/Login/CreateAccount
Content-Type: application/json
###
POST {{drones_HostAddress}}/api/Login/auth
Content-Type: application/json
###
GET {{drones_HostAddress}}/api/Drone/GetDrones
Accept: application/json
###
GET {{drones_HostAddress}}/api/Drone/GetOrders
Accept: application/json
###
POST {{drones_HostAddress}}/api/Login/Logout
